project:
  type: book
  output-dir: docs
  pre-render: R/data.R

book:
  title: "Systematic Review of Acceptability Judgment Tasks in Theoretical Linguistics"
  author: ["[Jason Grafmiller](mailto:j.grafmiller@bham.ac.uk)", "Dagmar Divjak", "Laura Rosseel"]
  # date: "today"
  # date-format: "D MMMM, YYYY"
  cover-image: "_images/laptop_cat.jpg"
  cover-image-alt: "Are we done yet?"
  repo-url: https://github.com/jasongraf1/ajt_review
  repo-branch: main
  site-url: https://jasongraf1.github.io/ajt_review/
  
  page-footer:
    left: |
      Website and annotation app Written by Jason Grafmiller.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - participants.qmd
    - part: "Design"
      chapters:
      - design.qmd
      - stimuli.qmd
      - task.qmd
    - part: "Rigor"
      chapters:
        - analysis.qmd
        - transparency.qmd
    - examples.qmd
    - references.qmd
    - text: "Checklist for authors"
      file: checklist.qmd
    - text: "Glossary"
      file: glossary.qmd

format:
  html:
    mainfont: 'Roboto'
    fontsize: 100%
    number-sections: false
    toc-title: "AJT review"
    theme: 
      light: 
        - flatly
        - custom.scss
      dark: 
        - darkly
        - custom_dark.scss
    css: custom_bib.css
    include-in-header: roboto_serif.html

execute:
  echo: false
  message: false
  warning: false
  freeze: auto
  fig-dpi: 300

editor: source
engine: knitr

#tbl-cap-location: top
#fig-cap-location: bottom
filters:
  - lightbox
lightbox: auto

knitr:
  opts_chunk: 
    tidy: styler
    dev: "svglite"

bibliography: [articles_selected_final.bib]
nocite: |
  @*
link-citations: true
csl: unified-style-linguistics.csl  # optional

